version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --region $AWS_REGION)
      - VERSION=$(date +%s)

  build:
    commands:
      - docker build -t www:$VERSION ./www
      - docker build -t cms:$VERSION ./cms
      - docker build -t nginx:$VERSION ./nginx

      - docker tag www:$VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/www:$VERSION
      - docker tag cms:$VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/cms:$VERSION
      - docker tag nginx:$VERSION $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/nginx:$VERSION

  post_build:
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/www:$VERSION
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/cms:$VERSION
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/nginx:$VERSION

      - sed "s/AWS_ACCOUNT_ID/$AWS_ACCOUNT_ID/g;s/VERSION/$VERSION/g;s/AWS_REGION/$AWS_REGION/g" Dockerrun.aws.template.json > Dockerrun.aws.json

artifacts:
  files:
    - .ebextensions/*
    - Dockerrun.aws.json
