version: '3.4'

services:
  # elasticsearch:
  #   environment:
  #     xpack.security.enabled: "false"
  #   image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
  #   ports:
  #     - 9200:9200

  mysql:
    environment:
      MYSQL_DATABASE: page
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
    image: mariadb:10.1
    ports:
      - 3306:3306
    volumes:
      - ./data/page.sql:/docker-entrypoint-initdb.d/page.sql

  www:
    build:
      args:
        SKIP_BUILD: 'true'
      context: ./www
    command: yarn run dev
    environment:
      NODE_ENV: development
    volumes:
      - /usr/src/app/node_modules
      - ./www:/usr/src/app

  cms:
    build:
      context: ./cms
    depends_on:
      - mysql
    environment:
      AUTH_KEY: 123
      AUTH_SALT: 123
      DBI_AWS_ACCESS_KEY_ID: 123
      DBI_AWS_SECRET_ACCESS_KEY: 123
      DB_NAME: page
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: mysql
      LOGGED_IN_KEY: 123
      LOGGED_IN_SALT: 123
      NONCE_KEY: 123
      NONCE_SALT: 123
      PHP_ENV: development
      S3_UPLOADS_BUCKET: ""
      S3_UPLOADS_BUCKET_URL: ""
      S3_UPLOADS_KEY: 123
      S3_UPLOADS_REGION: ""
      S3_UPLOADS_SECRET: ""
      SECURE_AUTH_KEY: 123
      SECURE_AUTH_SALT: 123
      WP_DEBUG: 'false'
    volumes:
      - ./cms/themes/page:/var/www/html/wp-content/themes/page
      - ./cms/uploads:/var/www/html/wp-content/uploads

  lb:
    build:
      context: ./lb
    links:
      - cms
      - www
    ports:
      - 80:80
