// flow-typed signature: bec780d11c389b4a4d2ee08d9e198e49
// flow-typed version: <<STUB>>/detect-node_v2.x.x/flow_v0.57.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'detect-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'detect-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'detect-node/index' {
  declare module.exports: $Exports<'detect-node'>;
}
declare module 'detect-node/index.js' {
  declare module.exports: $Exports<'detect-node'>;
}
